In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)
butter_sales=np.random.randint(0,50,(5,3))

In [3]:
butter_sales

array([[44, 47,  0],
       [ 3,  3, 39],
       [ 9, 19, 21],
       [36, 23,  6],
       [24, 24, 12]])

In [4]:
weekly_sales=pd.DataFrame(butter_sales,
                          index=["Mon","Tue","Wed","Thur","Fri"],
                          columns=["Almond Butter","Peanut Butter","Cashew Butter"])

In [5]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon              44             47              0
Tue               3              3             39
Wed               9             19             21
Thur             36             23              6
Fri              24             24             12

In [6]:
prices=np.array([10,8,12])

In [7]:
prices

array([10,  8, 12])

In [8]:
weekly_sales["Almond Butter"]

Mon     44
Tue      3
Wed      9
Thur    36
Fri     24
Name: Almond Butter, dtype: int32

In [9]:
array_1=np.array(weekly_sales["Almond Butter"])
array_2=np.array(weekly_sales["Peanut Butter"])
array_3=np.array(weekly_sales["Cashew Butter"])

In [10]:
array_4=np.array([array_1,array_2,array_3])

In [11]:
array_4

array([[44,  3,  9, 36, 24],
       [47,  3, 19, 23, 24],
       [ 0, 39, 21,  6, 12]])

In [12]:
array_4=array_4.T

In [13]:
array_4

array([[44, 47,  0],
       [ 3,  3, 39],
       [ 9, 19, 21],
       [36, 23,  6],
       [24, 24, 12]])

In [15]:
array_4.shape

(5, 3)

In [16]:
prices.shape

(3,)

In [19]:
x=np.dot(prices,array_4)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [14]:
array_4.shape

(5, 3)

In [15]:
prices.shape

(3,)

In [16]:
prices=prices.reshape(1,3)

In [17]:
prices.shape

(1, 3)

In [18]:
array_4.shape

(5, 3)

In [19]:
total_prices=prices.dot(array_4)

ValueError: shapes (1,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [20]:
total_prices=np.dot(prices,array_4.T)

In [21]:
total_prices

array([[816, 522, 494, 616, 576]])

In [22]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon              44             47              0
Tue               3              3             39
Wed               9             19             21
Thur             36             23              6
Fri              24             24             12

In [23]:
weekly_sales["Prices in $"]=total_prices.T

In [24]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Prices in $
Mon              44             47              0          816
Tue               3              3             39          522
Wed               9             19             21          494
Thur             36             23              6          616
Fri              24             24             12          576