In [1]:
import pandas as pd
import numpy as np

## Importing Dataset

In [2]:
heart_disease=pd.read_csv("C://Users//kamal//Desktop//Aalearn/heart-disease.csv")

In [3]:
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [4]:
heart_disease.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [5]:
heart_disease.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [6]:
from sklearn.model_selection import train_test_split

## Splitting the data

In [7]:
X=heart_disease.drop("target",axis=1)
y=heart_disease["target"]

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

## Trying model

In [13]:
np.random.seed=7
ran=RandomForestClassifier()
log=LogisticRegression(max_iter=1000)

In [21]:
ran.fit(X_train,y_train)

RandomForestClassifier()

In [22]:
log.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [23]:
ran.score(X_train,y_train)

1.0

In [24]:
log.score(X_train,y_train)

0.8429752066115702

In [25]:
ran_pred=ran.predict(X_test)

In [26]:
ran.score(X_test,y_test)

0.819672131147541

In [27]:
log_pred=log.predict(X_test)

In [28]:
log.score(X_test,y_test)

0.8032786885245902

## Accuracy Test

In [29]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score

In [30]:
def accuracy_test(y_true,y_preds):
    acc=accuracy_score(y_true,y_preds)
    pre=precision_score(y_true,y_preds)
    rec=recall_score(y_true,y_preds)
    f1=f1_score(y_true,y_preds)
    
    metric_dict:{"acc":round(acc,2),
                "pre":round(pre,2),
                "rec":round(rec,2),
                "f1":round(f1,2),
                }
    print(f"accuracy={acc*100:.2f}")
    print(f"precision={pre*100:.2f}")
    print(f"recall={rec*100:.2f}")
    print(f"f1={f1*100:.2f}")
    
    

In [31]:
accuracy_test(y_test,ran_pred)

accuracy=81.97
precision=77.78
recall=90.32
f1=83.58


In [32]:
accuracy_test(y_test,log_pred)

accuracy=80.33
precision=75.68
recall=90.32
f1=82.35


In [33]:
from sklearn.metrics import confusion_matrix

In [35]:
confusion_matrix(y_test,ran_pred)

array([[22,  8],
       [ 3, 28]], dtype=int64)

In [36]:
confusion_matrix(y_test,log_pred)

array([[21,  9],
       [ 3, 28]], dtype=int64)

In [41]:
pd.crosstab(y_test,ran_pred,
       rownames=["True Value"],
       colnames=["Predictedt Value"])

Predictedt Value   0   1
True Value              
0                 22   8
1                  3  28

In [45]:
confusion_matrix(y_test,log_pred)

array([[21,  9],
       [ 3, 28]], dtype=int64)

In [46]:
pd.crosstab(y_test,log_pred,
           rownames=["True Value"],
           colnames=["Predicted Value"])

Predicted Value   0   1
True Value             
0                21   9
1                 3  28

## Hence RandomForestClassifier is best for this dataset